Feature/pub 71 add error handler
deliveryhero/hfc-pubsub pull request #75
Opened 2021-09-30 21:41 UTC by ketan-saxena

PUB-71:
- Add handleError in Subscription class
- Add handleError method in SubscriberOptions for SubscriptionService
- Update example subscription

2021-10-01 04:22 UTC, rohit-gohri requested changes

2021-10-01 04:22 UTC, rohit-gohri commented on .changeset/real-nails-fetch.md
> +'@honestfoodcompany/pubsub': patch
I think this might be a minor, since we are adding a feature
```suggestion
'@honestfoodcompany/pubsub': minor
```

2021-10-01 04:22 UTC, rohit-gohri commented on src/subscriber/subscriber.ts
> +  }
let's not add new deprecated features. We'll only make this available in the SubscriberObject

2021-10-01 04:22 UTC, rohit-gohri commented on src/subscriber/subscriberV2.ts
> +      process.exit(1);
Let's not do process.exit as that will be a breaking change

2021-10-01 04:22 UTC, rohit-gohri commented on src/subscriber/subscriberV2.ts
> +  handleError?: (error: Error) => void;
I don't think this should go here, but would better work as a static function on the class like the init method. Since it ends up twice in individual subscriptions one as a method and then as an option

2021-10-01 04:22 UTC, rohit-gohri commented on src/client/googlePubSub.ts
> +    });
this would always be there right? since this is a wrapper function

2021-10-04 11:21 UTC, rohit-gohri approved these changes
LGTM with some nitpicks regarding defaults

2021-10-04 11:21 UTC, rohit-gohri commented on src/service/subscription.ts
> +  }
Let's rethrow the error in the default handler, so application can handle it on their own
```suggestion
  public static handleError(error: Error): void {
    // default error handling logic
    Logger.Instance.error({ error }, 'Received Unexpected Error');
    throw error;
  }
```

2021-10-04 11:21 UTC, rohit-gohri commented on docs/subscribing/Internal Error Handling.md
> +  }
Let's add an example similar to google docs:  https://googleapis.dev/nodejs/pubsub/latest/index.html#using-the-client-library
```suggestion
  handleError: function(error: Error): void {
    // internal error handling logic for subscriber
    console.error('Subscription error', error);
    // shutdown any connections here and exit
    process.exit(1);
  }
```

Similar handlers in other examples also

2021-10-05 09:43 UTC, ishan123456789 approved these changes

2021-10-05 09:45 UTC, merged